---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - route-version.yaml
configMapGenerator:
  - name: index-v1-1-0
    files:
      - index.html
generatorOptions:
  disableNameSuffixHash: true