
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: external-http
spec:
  gatewayClassName: gke-l7-regional-external-managed
  listeners:
  - name: gateway.american-broomstick
    hostname: "*.gateway.american-broomstick.com"
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: All