---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: App 1.
  sourceRepos:
    - '*'
  destinations:
    - namespace: app-1
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
