---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - route-version.yaml
configMapGenerator:
  - name: html-v1-0-0
    files:
      - html-v1-0-0.html
generatorOptions:
  disableNameSuffixHash: true